---
- name: install ntp package
  yum: name=ntp  state=present

- name: copy ntp configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 644
  notify: 
    - start ntpd
