---
- include: pre_requisite.yml
  when: not ceph_containerized_deployment

- include: start_restapi.yml
  when: not ceph_containerized_deployment

- include: ./docker/main.yml
  when: ceph_containerized_deployment
