---
- name: install apache
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd

- name: install rados gateway vhost
  template:
    src: ../../templates/rgw.conf
    dest: /etc/httpd/conf.d/rgw.conf
    owner: root
    group: root
  notify:
    - restart apache2 on red hat

- name: disable default site
  shell: sed -i "s/^[^+#]/#/g" /etc/httpd/conf.d/welcome.conf
  changed_when: false
  notify:
    - restart apache2
