---
- name: install ntp package
  yum: name=ntp  state=present

- name: copy ntp configuration
  template: >
    src=ntpd.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0644

- name: start ntp
  service: name=ntpd state=started
