---
- name: create working directory for installing calamari
  file: >
    path="{{ calamari_installation_dir }}"
    state=directory
    owner=root
    group=root
    mode=0755

- name: copy calamari-server file
  copy: >
    src=calamari-server-1.3.0.1.el7.centos.x86_64.rpm
    dest="{{ calamari_installation_dir }}"
    owner=root
    group=root
    mode=0644

- name: install calamari-server
  command: yum localinstall -y calamari-server-1.3.0.1.el7.centos.x86_64.rpm chdir={{ calamari_installation_dir }}

- name: copy calamari_ctl.py file
  copy: >
    src=calamari_ctl.py.new
    dest=/opt/calamari/venv/lib/python2.7/site-packages/calamari_cthulhu-0.1-py2.7.egg/cthulhu/calamari_ctl.py
    owner=root
    group=root
    mode=0644

- name: copy calamari-client file
  copy: >
    src=calamari-clients.tar.gz
    dest="{{ calamari_installation_dir }}"
    owner=root
    group=root
    mode=0644

- name: create working directory for installing calamari
  file: >
    path=/opt/calamari/webapp/content
    state=directory
    owner=root
    group=root
    mode=0755

- name: install calamari-client
  command: tar xfz {{ calamari_installation_dir }}/calamari-clients.tar.gz -C /opt/calamari/webapp/content/

- name: change calamari-client owner
  file: >
    path=/opt/calamari/webapp/content
    state=directory
    owner=apache
    group=apache
    recurse=yes

- name: initialize calamari-server
  command: calamari-ctl initialize
