---
- name: create rados gateway directories
  file: >
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode=0644
  with_items:
    - /var/lib/ceph/bootstrap-rgw
    - /var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}

- name: copy ceph admin key to create radosgw-key
  copy: >
    src={{ fetch_directory }}/{{ fsid }}/etc/ceph/ceph.client.admin.keyring
    dest=/etc/ceph/ceph.client.admin.keyring
    owner=root
    group=root
    mode=600
  when: cephx

- name: create rados gateway keyring
  command: >
    ceph auth get-or-create client.radosgw.{{ ansible_hostname }} osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/keyring
    creates=/var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/keyring
  changed_when: false
  when: cephx

- file: path=/etc/ceph/ceph.client.admin.keyring state=absent

- name: set rados gateway key permissions
  file: >
    path=/var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/keyring
    mode=0600
    owner=root
    group=root
  when: cephx

- name: activate rados gateway with upstart
  file: >
    path=/var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/{{ item }}
    state=touch
    owner=root
    group=root
    mode=0644
  with_items:
    - done
    - upstart
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: activate rados gateway with sysvinit
  file: >
    path=/var/lib/ceph/radosgw/ceph-rgw.{{ ansible_hostname }}/{{ item }}
    state=touch
    owner=root
    group=root
    mode=0644
  with_items:
    - done
    - sysvinit
  changed_when: false
  when: ansible_distribution != "Ubuntu"

- name: generate rados gateway sudoers file
  template: >
    src=ceph.j2
    dest=/etc/sudoers.d/ceph
    owner=root
    group=root
    mode=0400
  when: ansible_distribution != "Ubuntu"
