---
- name: copy diamond file
  copy: >
    src=diamond-v3.4.tar.gz
    dest="{{ calamari_installation_dir }}"
    owner=root
    group=root
    mode=0644

- name: un-tar diamond
  command: tar xfz diamond-v3.4.tar.gz chdir={{ calamari_installation_dir }}

- name: install diamond
  command: python setup.py install chdir={{ calamari_installation_dir }}/Diamond-3.4

- name: copy init file of diamond
  command: cp -a bin/init.d/diamond /etc/init.d/diamond chdir={{ calamari_installation_dir }}/Diamond-3.4

- name: copy diamond ceph collector file
  template:
    src: CephCollector.conf.j2
    dest: /etc/diamond/collectors/CephCollector.conf
    owner: root
    group: root
    mode: 655

- name: copy diamond network collector file
  template:
    src: NetworkCollector.conf.j2
    dest: /etc/diamond/collectors/NetworkCollector.conf
    owner: root
    group: root
    mode: 644
 
- name: copy diamond configuation file
  template:
    src: diamond.conf.j2
    dest: /etc/diamond/diamond.conf
    owner: root
    group: root
    mode: 644
  notify:
    - restart diamond
