---
- name: create bootstrap directories
  file: >
    path=/var/lib/ceph/bootstrap-{{ item }}
    state=directory
  with_items:
    - osd
    - mds
    - rgw

# NOTE (leseb): for version 1.1.0 because https://github.com/ansible/ansible-modules-core/issues/1227
- name: install docker-py
  pip: >
    name=docker-py
    version=1.1.0
